server:
  port: 8081

spring:
  datasource:
    #    url: jdbc:mariadb://localhost:3306/eulzi
    # 도커 데스크톱용 URL 설정(https://docs.docker.com/desktop/mac/networking/)
    url: jdbc:mariadb://host.docker.internal:3306/eulzi
    username: eulzi
    password: eulzi
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate:
      ddl-auto: none